const API_KEY_MAX_ACTIVE = 10;
const API_KEY_TTL_MS = 90 * 24 * 60 * 60 * 1_000;
const API_KEY_WINDOW_MS = 60_000;
const API_KEY_WINDOW_LIMIT = 60;

export { API_KEY_MAX_ACTIVE, API_KEY_TTL_MS, API_KEY_WINDOW_MS, API_KEY_WINDOW_LIMIT };
