const dateTime = { type: 'string', format: 'date-time' };
const nullableDateTime = { oneOf: [dateTime, { type: 'null' }] };
const nullableString = { oneOf: [{ type: 'string' }, { type: 'null' }] };
const objectId = { type: 'string', pattern: '^[a-fA-F0-9]{24}$' };
const stellarAddress = {
  type: 'string',
  pattern: '^G[A-Z2-7]{55}$',
  example: 'GCFIRY65OQE7DFP5KLNS2PF2LVZMUZYJX4OZIEQ36N2IQANUB5XVYOJR',
};
const numberMetrics = { type: 'object', additionalProperties: { type: 'number' } };
const scanSummary = {
  type: 'object',
  required: [
    'scope',
    'operationCount',
    'initiatedOperationCount',
    'relatedOperationCount',
    'distinctTransactionCount',
    'activeDayCount',
    'firstObservedAt',
    'lastObservedAt',
    'operationTypeCounts',
    'sentPaymentCount',
    'receivedPaymentCount',
    'selfPaymentCount',
    'trustlineChangeCount',
    'offerActionCount',
    'contractInvocationCount',
  ],
  properties: {
    scope: { type: 'string', enum: ['page', 'scanned_pages'] },
    operationCount: { type: 'integer', minimum: 0 },
    initiatedOperationCount: { type: 'integer', minimum: 0 },
    relatedOperationCount: { type: 'integer', minimum: 0 },
    distinctTransactionCount: { type: 'integer', minimum: 0 },
    activeDayCount: { type: 'integer', minimum: 0 },
    firstObservedAt: nullableDateTime,
    lastObservedAt: nullableDateTime,
    operationTypeCounts: { type: 'object', additionalProperties: { type: 'integer' } },
    sentPaymentCount: { type: 'integer', minimum: 0 },
    receivedPaymentCount: { type: 'integer', minimum: 0 },
    selfPaymentCount: { type: 'integer', minimum: 0 },
    trustlineChangeCount: { type: 'integer', minimum: 0 },
    offerActionCount: { type: 'integer', minimum: 0 },
    contractInvocationCount: { type: 'integer', minimum: 0 },
  },
};

const openApiComponents = {
  securitySchemes: {
    bearerAuth: { type: 'http', scheme: 'bearer', bearerFormat: 'JWT' },
    sessionCookie: { type: 'apiKey', in: 'cookie', name: 'lumenrise_session' },
    developerApiKey: { type: 'apiKey', in: 'header', name: 'X-API-Key' },
  },
  schemas: {
    StellarAddress: stellarAddress,
    ObjectId: objectId,
    ErrorResponse: {
      type: 'object',
      required: ['status', 'message', 'result'],
      properties: {
        status: { type: 'string', const: 'error' },
        message: { type: 'string' },
        result: { type: 'object', additionalProperties: false },
      },
    },
    EmptyResult: { type: 'object', additionalProperties: false },
    DeveloperApiKey: {
      type: 'object',
      required: ['id', 'label', 'prefix', 'expiresAt', 'revokedAt', 'createdAt'],
      properties: {
        id: objectId,
        label: { type: 'string' },
        prefix: { type: 'string' },
        expiresAt: dateTime,
        revokedAt: nullableDateTime,
        createdAt: dateTime,
      },
    },
    DeveloperApiKeyCreated: {
      allOf: [
        { $ref: '#/components/schemas/DeveloperApiKey' },
        {
          type: 'object',
          required: ['apiKey'],
          properties: { apiKey: { type: 'string', description: 'Shown once. Store it securely.' } },
        },
      ],
    },
    DeveloperApiKeyList: {
      type: 'object',
      required: ['keys'],
      properties: {
        keys: { type: 'array', items: { $ref: '#/components/schemas/DeveloperApiKey' } },
      },
    },
    SybilEvidence: {
      type: 'object',
      required: [
        'identityId',
        'algorithmVersion',
        'generatedAt',
        'assessment',
        'corroboration',
        'observations',
        'limitations',
      ],
      properties: {
        identityId: objectId,
        algorithmVersion: { type: 'string', const: 'sybil-evidence-v2' },
        generatedAt: dateTime,
        assessment: { type: 'string', const: 'not_assessed' },
        corroboration: {
          type: 'object',
          description:
            'Activity corroboration across GitHub, GitLab and the registered primary Stellar wallet. Not a Sybil risk score or policy input.',
          required: ['algorithmVersion', 'status', 'score', 'missingSources', 'signals'],
          properties: {
            algorithmVersion: { type: 'string', const: 'activity-corroboration-v1' },
            status: { type: 'string', enum: ['available', 'insufficient_data'] },
            score: { oneOf: [{ type: 'number', minimum: 0, maximum: 100 }, { type: 'null' }] },
            missingSources: {
              type: 'array',
              items: { type: 'string', enum: ['github', 'gitlab', 'stellar'] },
            },
            signals: {
              type: 'array',
              items: {
                type: 'object',
                required: ['source', 'key', 'rawValue', 'normalizedValue', 'sourceId'],
                properties: {
                  source: { type: 'string', enum: ['github', 'gitlab', 'stellar'] },
                  key: { type: 'string' },
                  rawValue: { type: 'number', minimum: 0 },
                  normalizedValue: { type: 'number', minimum: 0, maximum: 100 },
                  sourceId: objectId,
                },
              },
            },
          },
        },
        observations: {
          type: 'array',
          items: {
            type: 'object',
            required: [
              'source',
              'ownership',
              'coverage',
              'sourceIds',
              'observedAt',
              'sourceVersion',
            ],
            properties: {
              source: { type: 'string', enum: ['stellar', 'github', 'gitlab', 'x'] },
              ownership: {
                type: 'string',
                enum: ['wallet_registration', 'oauth_connection', 'not_connected'],
              },
              coverage: { type: 'string', enum: ['complete', 'partial', 'missing'] },
              sourceIds: { type: 'array', items: { type: 'string' } },
              observedAt: nullableDateTime,
              sourceVersion: nullableString,
            },
          },
        },
        limitations: { type: 'array', items: { type: 'string' } },
      },
    },
    PolicyRule: {
      type: 'object',
      required: ['dimension', 'minScore', 'maxAgeSeconds'],
      additionalProperties: false,
      properties: {
        dimension: { type: 'string', enum: ['developer', 'social', 'stellar'] },
        minScore: { type: 'number', minimum: 0, maximum: 100 },
        maxAgeSeconds: { type: 'integer', minimum: 60, maximum: 31_536_000 },
      },
    },
    PolicyDefinition: {
      type: 'object',
      required: ['key', 'version', 'match', 'rules'],
      additionalProperties: false,
      properties: {
        key: { type: 'string', pattern: '^[a-z][a-z0-9-]{2,63}$' },
        version: { type: 'integer', minimum: 1 },
        match: { type: 'string', enum: ['all', 'any'] },
        rules: {
          type: 'array',
          minItems: 1,
          maxItems: 3,
          items: { $ref: '#/components/schemas/PolicyRule' },
        },
      },
    },
    Policy: {
      allOf: [
        { $ref: '#/components/schemas/PolicyDefinition' },
        {
          type: 'object',
          required: ['id', 'createdAt'],
          properties: { id: objectId, createdAt: dateTime },
        },
      ],
    },
    PolicyList: {
      type: 'object',
      required: ['policies'],
      properties: {
        policies: { type: 'array', items: { $ref: '#/components/schemas/Policy' } },
      },
    },
    PolicyEvaluation: {
      type: 'object',
      required: ['policyKey', 'policyVersion', 'decision', 'evaluatedAt', 'expiresAt', 'rules'],
      properties: {
        policyKey: { type: 'string' },
        policyVersion: { type: 'integer' },
        decision: { type: 'string', enum: ['eligible', 'ineligible', 'insufficient_data'] },
        evaluatedAt: dateTime,
        expiresAt: nullableDateTime,
        rules: {
          type: 'array',
          items: {
            type: 'object',
            required: [
              'dimension',
              'minScore',
              'maxAgeSeconds',
              'outcome',
              'reason',
              'actualScore',
              'algorithmVersion',
              'calculatedAt',
              'sourceIds',
              'validUntil',
            ],
            properties: {
              dimension: { type: 'string', enum: ['developer', 'social', 'stellar'] },
              minScore: { type: 'number' },
              maxAgeSeconds: { type: 'integer' },
              outcome: { type: 'string', enum: ['pass', 'fail', 'unknown'] },
              reason: {
                type: 'string',
                enum: [
                  'threshold_met',
                  'below_threshold',
                  'score_unavailable',
                  'score_incomplete',
                  'score_stale',
                ],
              },
              actualScore: { oneOf: [{ type: 'number' }, { type: 'null' }] },
              algorithmVersion: nullableString,
              calculatedAt: nullableDateTime,
              sourceIds: { type: 'array', items: { type: 'string' } },
              validUntil: nullableDateTime,
            },
          },
        },
      },
    },
    HealthResult: {
      type: 'object',
      required: ['service', 'state', 'timestamp', 'uptime'],
      properties: {
        service: { type: 'string', const: 'lumenrise-api' },
        state: { type: 'string', const: 'ok' },
        timestamp: dateTime,
        uptime: { type: 'number', minimum: 0 },
      },
    },
    WalletChallengeResult: {
      type: 'object',
      required: ['challengeId', 'address', 'purpose', 'message', 'networkPassphrase', 'expiresAt'],
      properties: {
        challengeId: objectId,
        address: stellarAddress,
        purpose: { type: 'string', enum: ['register', 'login'] },
        message: {
          type: 'string',
          description:
            'Sign these exact bytes with the wallet signMessage method. Do not submit a transaction.',
        },
        networkPassphrase: { type: 'string' },
        expiresAt: dateTime,
      },
    },
    WalletAuthResult: {
      type: 'object',
      required: ['identityId', 'address', 'name', 'accessToken', 'tokenType', 'expiresAt'],
      properties: {
        identityId: objectId,
        address: stellarAddress,
        name: nullableString,
        accessToken: { type: 'string', description: 'Bearer JWT. Keep it private.' },
        tokenType: { type: 'string', const: 'Bearer' },
        expiresAt: dateTime,
      },
    },
    SessionResult: {
      type: 'object',
      required: ['identityId', 'expiresAt'],
      properties: { identityId: objectId, expiresAt: dateTime },
    },
    IntegrationSyncJob: {
      type: 'object',
      required: [
        'id',
        'provider',
        'status',
        'attempts',
        'maxAttempts',
        'scheduledAt',
        'startedAt',
        'completedAt',
        'lastError',
        'resultSnapshotId',
      ],
      properties: {
        id: objectId,
        provider: { type: 'string', enum: ['github', 'gitlab', 'x'] },
        status: { type: 'string', enum: ['queued', 'running', 'completed', 'failed', 'cancelled'] },
        attempts: { type: 'integer', minimum: 0 },
        maxAttempts: { type: 'integer', minimum: 1 },
        scheduledAt: dateTime,
        startedAt: nullableDateTime,
        completedAt: nullableDateTime,
        lastError: nullableString,
        resultSnapshotId: { oneOf: [objectId, { type: 'null' }] },
      },
    },
    Connection: {
      type: 'object',
      required: [
        'provider',
        'username',
        'displayName',
        'profileUrl',
        'avatarUrl',
        'connectedAt',
        'lastSyncedAt',
        'data',
        'sync',
      ],
      properties: {
        provider: { type: 'string', enum: ['github', 'gitlab', 'x'] },
        username: { type: 'string' },
        displayName: nullableString,
        profileUrl: nullableString,
        avatarUrl: nullableString,
        connectedAt: dateTime,
        lastSyncedAt: nullableDateTime,
        data: {
          oneOf: [
            {
              type: 'object',
              required: ['status', 'dataVersion', 'collectedAt'],
              properties: {
                status: { type: 'string', enum: ['complete', 'partial'] },
                dataVersion: { type: 'string' },
                collectedAt: dateTime,
              },
            },
            { type: 'null' },
          ],
        },
        sync: { oneOf: [{ $ref: '#/components/schemas/IntegrationSyncJob' }, { type: 'null' }] },
      },
    },
    ConnectionsResult: {
      type: 'object',
      required: ['connections'],
      properties: {
        connections: { type: 'array', items: { $ref: '#/components/schemas/Connection' } },
      },
    },
    ReputationSignal: {
      type: 'object',
      required: [
        'provider',
        'key',
        'rawValue',
        'normalization',
        'scale',
        'baseWeight',
        'normalizedScore',
        'weight',
        'contribution',
        'observedAt',
      ],
      properties: {
        provider: { type: 'string', enum: ['github', 'gitlab', 'x'] },
        key: { type: 'string' },
        rawValue: { type: 'number' },
        normalization: { type: 'string', const: 'diminishing_returns' },
        scale: { type: 'number' },
        baseWeight: { type: 'number' },
        normalizedScore: { type: 'number' },
        weight: { type: 'number' },
        contribution: { type: 'number' },
        observedAt: dateTime,
      },
    },
    ReputationScore: {
      type: 'object',
      required: [
        'category',
        'status',
        'algorithmVersion',
        'score',
        'signals',
        'sources',
        'calculatedAt',
      ],
      properties: {
        category: { type: 'string', enum: ['developer', 'social'] },
        status: { type: 'string', enum: ['complete', 'partial', 'failed'] },
        algorithmVersion: { type: 'string' },
        score: { oneOf: [{ type: 'number', minimum: 0, maximum: 100 }, { type: 'null' }] },
        signals: { type: 'array', items: { $ref: '#/components/schemas/ReputationSignal' } },
        sources: {
          type: 'array',
          items: {
            type: 'object',
            required: ['provider', 'snapshotId', 'dataVersion', 'collectedAt'],
            properties: {
              provider: { type: 'string', enum: ['github', 'gitlab', 'x'] },
              snapshotId: objectId,
              dataVersion: { type: 'string' },
              collectedAt: dateTime,
            },
          },
        },
        calculatedAt: dateTime,
      },
    },
    ReputationProfile: {
      type: 'object',
      required: ['identity', 'developer', 'social', 'stellar'],
      properties: {
        identity: {
          type: 'object',
          required: ['id', 'name', 'primaryWalletAddress'],
          properties: {
            id: { $ref: '#/components/schemas/ObjectId' },
            name: nullableString,
            primaryWalletAddress: {
              oneOf: [{ $ref: '#/components/schemas/StellarAddress' }, { type: 'null' }],
            },
          },
        },
        developer: { oneOf: [{ $ref: '#/components/schemas/ReputationScore' }, { type: 'null' }] },
        social: { oneOf: [{ $ref: '#/components/schemas/ReputationScore' }, { type: 'null' }] },
        stellar: { oneOf: [{ $ref: '#/components/schemas/StellarReputation' }, { type: 'null' }] },
      },
    },
    GitHubSnapshot: {
      type: 'object',
      required: [
        'provider',
        'status',
        'dataVersion',
        'username',
        'coverage',
        'metrics',
        'contributionPeriods',
        'collectedAt',
      ],
      properties: {
        provider: { type: 'string', const: 'github' },
        status: { type: 'string', enum: ['complete', 'partial'] },
        dataVersion: { type: 'string' },
        username: { type: 'string' },
        coverage: {
          type: 'object',
          required: ['profile', 'contributions', 'repositories'],
          properties: {
            profile: { type: 'boolean' },
            contributions: { type: 'boolean' },
            repositories: { type: 'boolean' },
          },
        },
        metrics: numberMetrics,
        contributionPeriods: {
          type: 'array',
          items: {
            type: 'object',
            required: ['key', 'from', 'to'],
            properties: {
              key: { type: 'string' },
              from: dateTime,
              to: dateTime,
              totalContributions: { type: 'integer' },
              commitContributions: { type: 'integer' },
              issueContributions: { type: 'integer' },
              pullRequestContributions: { type: 'integer' },
              pullRequestReviewContributions: { type: 'integer' },
              repositoryContributions: { type: 'integer' },
              restrictedContributions: { type: 'integer' },
            },
            additionalProperties: { type: 'integer' },
          },
        },
        collectedAt: dateTime,
      },
    },
    GitLabSnapshot: {
      type: 'object',
      required: [
        'provider',
        'status',
        'dataVersion',
        'username',
        'coverage',
        'metrics',
        'activityFrom',
        'activityTo',
        'collectedAt',
      ],
      properties: {
        provider: { type: 'string', const: 'gitlab' },
        status: { type: 'string', enum: ['complete', 'partial'] },
        dataVersion: { type: 'string' },
        username: { type: 'string' },
        coverage: {
          type: 'object',
          required: ['profile', 'projects', 'contributions', 'associations'],
          properties: {
            profile: { type: 'boolean' },
            projects: { type: 'boolean' },
            contributions: { type: 'boolean' },
            associations: { type: 'boolean' },
          },
        },
        metrics: numberMetrics,
        activityFrom: nullableDateTime,
        activityTo: dateTime,
        collectedAt: dateTime,
      },
    },
    XSnapshot: {
      type: 'object',
      required: [
        'provider',
        'status',
        'dataVersion',
        'username',
        'coverage',
        'metrics',
        'activityFrom',
        'activityTo',
        'collectedAt',
      ],
      properties: {
        provider: { type: 'string', const: 'x' },
        status: { type: 'string', enum: ['complete', 'partial'] },
        dataVersion: { type: 'string' },
        username: { type: 'string' },
        coverage: {
          type: 'object',
          required: ['profile', 'posts'],
          properties: {
            profile: { type: 'boolean' },
            posts: { type: 'boolean' },
          },
        },
        metrics: numberMetrics,
        activityFrom: nullableDateTime,
        activityTo: dateTime,
        collectedAt: dateTime,
      },
    },
    GitHubRepositories: {
      type: 'object',
      required: ['items', 'nextCursor'],
      properties: {
        items: {
          type: 'array',
          items: {
            type: 'object',
            required: ['repositoryId', 'nameWithOwner'],
            properties: {
              repositoryId: { type: 'string' },
              nameWithOwner: { type: 'string' },
              isFork: { type: 'boolean' },
              isArchived: { type: 'boolean' },
              starCount: { type: 'integer' },
              forkCount: { type: 'integer' },
              watcherCount: { type: 'integer' },
              openIssueCount: { type: 'integer' },
              mergedPullRequestCount: { type: 'integer' },
              releaseCount: { type: 'integer' },
              primaryLanguage: nullableString,
              repositoryCreatedAt: dateTime,
              lastPushedAt: nullableDateTime,
            },
          },
        },
        nextCursor: { oneOf: [objectId, { type: 'null' }] },
      },
    },
    GitLabProjects: {
      type: 'object',
      required: ['items', 'nextCursor'],
      properties: {
        items: {
          type: 'array',
          items: {
            type: 'object',
            required: ['projectId', 'nameWithNamespace'],
            properties: {
              projectId: { type: 'string' },
              nameWithNamespace: { type: 'string' },
              pathWithNamespace: { type: 'string' },
              namespaceKind: { type: 'string' },
              visibility: { type: 'string', enum: ['private', 'internal', 'public'] },
              isOwned: { type: 'boolean' },
              isContributed: { type: 'boolean' },
              isFork: { type: 'boolean' },
              isArchived: { type: 'boolean' },
              starCount: { type: 'integer' },
              forkCount: { type: 'integer' },
              openIssueCount: { type: 'integer' },
              topics: { type: 'array', items: { type: 'string' } },
              webUrl: { type: 'string', format: 'uri' },
              description: nullableString,
              projectCreatedAt: dateTime,
              lastActivityAt: dateTime,
            },
          },
        },
        nextCursor: { oneOf: [objectId, { type: 'null' }] },
      },
    },
    GitLabEvents: {
      type: 'object',
      required: ['items', 'nextCursor'],
      properties: {
        items: {
          type: 'array',
          items: {
            type: 'object',
            required: ['eventId', 'projectId'],
            properties: {
              eventId: { type: 'string' },
              projectId: nullableString,
              actionName: { type: 'string' },
              targetId: nullableString,
              targetIid: nullableString,
              targetType: nullableString,
              targetTitle: nullableString,
              commitCount: { oneOf: [{ type: 'integer' }, { type: 'null' }] },
              refType: nullableString,
              ref: nullableString,
              eventCreatedAt: dateTime,
            },
          },
        },
        nextCursor: { oneOf: [objectId, { type: 'null' }] },
      },
    },
    StellarAccountOverview: {
      type: 'object',
      required: [
        'address',
        'ownershipVerified',
        'sequence',
        'subentryCount',
        'sponsoringCount',
        'sponsoredCount',
        'signerCount',
        'thresholds',
        'homeDomain',
        'lastModifiedLedger',
        'balances',
        'checkedAt',
      ],
      properties: {
        address: stellarAddress,
        ownershipVerified: { type: 'boolean', const: false },
        sequence: { type: 'string' },
        subentryCount: { type: 'integer' },
        sponsoringCount: { type: 'integer' },
        sponsoredCount: { type: 'integer' },
        signerCount: { type: 'integer' },
        thresholds: {
          type: 'object',
          properties: {
            low: { type: 'integer' },
            medium: { type: 'integer' },
            high: { type: 'integer' },
          },
        },
        homeDomain: nullableString,
        lastModifiedLedger: { type: 'integer' },
        balances: {
          type: 'array',
          items: {
            type: 'object',
            properties: {
              assetType: { type: 'string' },
              assetCode: nullableString,
              assetIssuer: nullableString,
              balance: { type: 'string' },
              buyingLiabilities: nullableString,
              sellingLiabilities: nullableString,
              limit: nullableString,
              isAuthorized: { oneOf: [{ type: 'boolean' }, { type: 'null' }] },
            },
          },
        },
        checkedAt: dateTime,
      },
    },
    StellarOperations: {
      type: 'object',
      required: [
        'address',
        'ownershipVerified',
        'order',
        'limit',
        'items',
        'summary',
        'nextCursor',
      ],
      properties: {
        address: stellarAddress,
        ownershipVerified: { type: 'boolean', const: false },
        order: { type: 'string', enum: ['asc', 'desc'] },
        limit: { type: 'integer' },
        items: {
          type: 'array',
          items: {
            type: 'object',
            properties: {
              pagingToken: { type: 'string' },
              type: { type: 'string' },
              typeId: { type: 'integer' },
              createdAt: dateTime,
              transactionHash: { type: 'string' },
              sourceAccount: stellarAddress,
              details: { type: 'object', additionalProperties: true },
            },
          },
        },
        summary: scanSummary,
        nextCursor: nullableString,
      },
    },
    StellarScan: {
      type: 'object',
      required: [
        'id',
        'address',
        'ownershipVerified',
        'source',
        'status',
        'availableHistoryScanned',
        'cursor',
        'pagesProcessed',
        'summary',
        'lastProcessedAt',
        'completedAt',
        'lastError',
      ],
      properties: {
        id: objectId,
        address: stellarAddress,
        ownershipVerified: { type: 'boolean' },
        source: { type: 'string', const: 'horizon' },
        status: { type: 'string', enum: ['queued', 'running', 'completed', 'failed'] },
        availableHistoryScanned: {
          type: 'boolean',
          description: 'Only history available from the configured Horizon server.',
        },
        cursor: nullableString,
        pagesProcessed: { type: 'integer', minimum: 0 },
        summary: scanSummary,
        lastProcessedAt: nullableDateTime,
        completedAt: nullableDateTime,
        lastError: nullableString,
      },
    },
    StellarActivityScore: {
      type: 'object',
      required: [
        'address',
        'ownershipVerified',
        'eligibilityProof',
        'source',
        'scanId',
        'algorithmVersion',
        'availableHistoryScanned',
        'pagesProcessed',
        'score',
        'signals',
        'calculatedAt',
      ],
      properties: {
        address: stellarAddress,
        ownershipVerified: { type: 'boolean' },
        eligibilityProof: { type: 'boolean', const: false },
        source: { type: 'string', const: 'horizon' },
        scanId: objectId,
        algorithmVersion: { type: 'string' },
        availableHistoryScanned: { type: 'boolean', const: true },
        pagesProcessed: { type: 'integer' },
        score: { type: 'number', minimum: 0, maximum: 100 },
        signals: {
          type: 'array',
          items: {
            type: 'object',
            required: [
              'key',
              'rawValue',
              'scale',
              'baseWeight',
              'normalizedScore',
              'weight',
              'contribution',
            ],
            properties: {
              key: { type: 'string' },
              rawValue: { type: 'number' },
              scale: { type: 'number' },
              baseWeight: { type: 'number' },
              normalizedScore: { type: 'number' },
              weight: { type: 'number' },
              contribution: { type: 'number' },
            },
          },
        },
        calculatedAt: dateTime,
      },
    },
    StellarReputation: {
      type: 'object',
      required: ['address', 'ownershipVerified', 'scanStatus', 'scan', 'score'],
      properties: {
        address: stellarAddress,
        ownershipVerified: { type: 'boolean', const: true },
        scanStatus: {
          type: 'string',
          enum: ['not_started', 'queued', 'running', 'completed', 'failed'],
        },
        scan: { oneOf: [{ $ref: '#/components/schemas/StellarScan' }, { type: 'null' }] },
        score: { oneOf: [{ $ref: '#/components/schemas/StellarActivityScore' }, { type: 'null' }] },
      },
    },
    SorobanEvidence: {
      type: 'object',
      required: [
        'scanId',
        'address',
        'ownershipVerified',
        'source',
        'scanStatus',
        'availableHistoryScanned',
        'coverage',
        'items',
        'nextCursor',
      ],
      properties: {
        scanId: objectId,
        address: stellarAddress,
        ownershipVerified: { type: 'boolean', const: false },
        source: { type: 'string', const: 'horizon_and_stellar_rpc' },
        scanStatus: { type: 'string', enum: ['queued', 'running', 'completed', 'failed'] },
        availableHistoryScanned: { type: 'boolean' },
        coverage: {
          type: 'object',
          required: [
            'discoveredTransactions',
            'rpcQueued',
            'rpcRunning',
            'rpcSuccess',
            'rpcFailed',
            'rpcNotFound',
            'rpcUnavailable',
          ],
          properties: Object.fromEntries(
            [
              'discoveredTransactions',
              'rpcQueued',
              'rpcRunning',
              'rpcSuccess',
              'rpcFailed',
              'rpcNotFound',
              'rpcUnavailable',
            ].map((key) => [key, { type: 'integer', minimum: 0 }]),
          ),
        },
        items: {
          type: 'array',
          items: {
            type: 'object',
            required: [
              'transactionHash',
              'operationIds',
              'initiatedOperation',
              'observedAt',
              'rpcStatus',
              'attempts',
              'ledger',
              'returnValueXdr',
              'envelope',
              'events',
            ],
            properties: {
              transactionHash: { type: 'string' },
              operationIds: { type: 'array', items: { type: 'string' } },
              initiatedOperation: { type: 'boolean' },
              observedAt: dateTime,
              rpcStatus: {
                type: 'string',
                enum: ['queued', 'running', 'success', 'failed', 'not_found', 'unavailable'],
              },
              attempts: { type: 'integer', minimum: 0 },
              ledger: { oneOf: [{ type: 'integer' }, { type: 'null' }] },
              returnValueXdr: nullableString,
              envelope: {
                description:
                  'Decoded envelope evidence, or null if RPC did not return a parseable envelope. No signature or ownership inference.',
                oneOf: [
                  { type: 'null' },
                  {
                    type: 'object',
                    required: ['envelopeType', 'transactionSource', 'feeSource', 'operations'],
                    properties: {
                      envelopeType: { type: 'string' },
                      transactionSource: { type: 'string' },
                      feeSource: nullableString,
                      operations: {
                        type: 'array',
                        description:
                          'Invoke-host-function operations only; operationIndex is zero-based in the inner transaction.',
                        items: {
                          type: 'object',
                          required: [
                            'operationIndex',
                            'sourceAccount',
                            'explicitSourceAccount',
                            'hostFunctionType',
                            'contractAddress',
                            'functionName',
                            'authorizations',
                          ],
                          properties: {
                            operationIndex: { type: 'integer', minimum: 0 },
                            sourceAccount: {
                              type: 'string',
                              description: 'Effective operation source, not a verified signer.',
                            },
                            explicitSourceAccount: nullableString,
                            hostFunctionType: { type: 'string' },
                            contractAddress: nullableString,
                            functionName: nullableString,
                            authorizations: {
                              type: 'array',
                              items: {
                                type: 'object',
                                required: ['credentialType', 'address', 'delegates', 'invocations'],
                                properties: {
                                  credentialType: { type: 'string' },
                                  address: nullableString,
                                  delegates: {
                                    type: 'array',
                                    description:
                                      'Addresses in a delegated credential tree, not verified signers.',
                                    items: {
                                      type: 'object',
                                      required: ['address', 'depth'],
                                      properties: {
                                        address: { type: 'string' },
                                        depth: { type: 'integer', minimum: 0 },
                                      },
                                    },
                                  },
                                  invocations: {
                                    type: 'array',
                                    items: {
                                      type: 'object',
                                      required: [
                                        'depth',
                                        'type',
                                        'contractAddress',
                                        'functionName',
                                      ],
                                      properties: {
                                        depth: { type: 'integer', minimum: 0 },
                                        type: { type: 'string' },
                                        contractAddress: nullableString,
                                        functionName: nullableString,
                                      },
                                    },
                                  },
                                },
                              },
                            },
                          },
                        },
                      },
                    },
                  },
                ],
              },
              events: {
                type: 'array',
                items: {
                  type: 'object',
                  required: ['operationIndex', 'eventIndex', 'contractId', 'eventXdr'],
                  properties: {
                    operationIndex: { type: 'integer', minimum: 0 },
                    eventIndex: { type: 'integer', minimum: 0 },
                    contractId: nullableString,
                    eventXdr: { type: 'string', description: 'Base64-encoded ContractEvent XDR.' },
                  },
                },
              },
            },
          },
        },
        nextCursor: { oneOf: [objectId, { type: 'null' }] },
      },
    },
  },
  responses: {
    BadRequest: {
      description: 'Invalid request.',
      content: { 'application/json': { schema: { $ref: '#/components/schemas/ErrorResponse' } } },
    },
    Unauthorized: {
      description: 'Authentication is required or invalid.',
      content: { 'application/json': { schema: { $ref: '#/components/schemas/ErrorResponse' } } },
    },
    NotFound: {
      description: 'The requested resource is unavailable.',
      content: { 'application/json': { schema: { $ref: '#/components/schemas/ErrorResponse' } } },
    },
    Conflict: {
      description: 'The request conflicts with current state.',
      content: { 'application/json': { schema: { $ref: '#/components/schemas/ErrorResponse' } } },
    },
    TooManyRequests: {
      description: 'The request exceeded a cooldown or quota. Retry-After is in seconds.',
      headers: { 'Retry-After': { schema: { type: 'integer', minimum: 1 } } },
      content: { 'application/json': { schema: { $ref: '#/components/schemas/ErrorResponse' } } },
    },
    BadGateway: {
      description: 'The upstream service is unavailable.',
      content: { 'application/json': { schema: { $ref: '#/components/schemas/ErrorResponse' } } },
    },
    ServiceUnavailable: {
      description: 'The service is temporarily unavailable.',
      content: { 'application/json': { schema: { $ref: '#/components/schemas/ErrorResponse' } } },
    },
  },
} as const;

export default openApiComponents;
